cache:
  paths:
    - node_modules/

stages:
  - build
  - register
  - deploy
  - publish


build-asset:
  stage: build
  image: node:16-alpine3.16
  only:
    - master
    - develop
    - review
  script:
    - npm ci
    - cp config/user-config.sample.js config/user-config.js
    - npm run build
  artifacts:
    paths:
      - dist

################################################
# NO MORE MODIFICATIONS BELOW THIS COMMENT !!! #
################################################

register develop as latest:
  stage: register
  tags:
    - dind
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  only:
    - develop
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE":latest .
    - docker push "$CI_REGISTRY_IMAGE":latest
    - echo IMAGE_DIGEST=$(docker inspect --format="{{index .RepoDigests 0}}" "$CI_REGISTRY_IMAGE":latest | rev | cut -d":" -f1 | rev) >> digest.env
  artifacts:
    reports:
      dotenv: digest.env

deploy to gcp-staging:
  variables:
    TF_IMAGES: "vars/images.tfvars"
    TF_PROJECT: "gitlab.fokus.fraunhofer.de/open-data-bayern/misc/terraform.git"
    TF_VAR_NAME: "piveau_ui_dpi_v3_digest"
  stage: deploy
  dependencies:
    - register develop as latest
  image: alpine/git-tag
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" && $IMAGE_DIGEST != ""
  before_script:
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git remote set-url origin "https://gitlab-token:$TERRAFORM_PUBLISH_TOKEN@$TF_PROJECT"
    - git fetch origin main && git reset --hard FETCH_HEAD
  script:
    - sed -i -e "s/^$TF_VAR_NAME = .*/$TF_VAR_NAME = \"$IMAGE_DIGEST\"/g" $TF_IMAGES
    - git add $TF_IMAGES
    - git commit -m "CI Update \"$CI_PROJECT_NAME\" image to sha256:${IMAGE_DIGEST:0:6}"
    - git push origin HEAD:main
