server {
    listen         8080;
    server_name    localhost;

    gzip on;
    gzip_static on;
    gzip_disable "msie6";

    gzip_comp_level 6;
    gzip_min_length 1100;
    gzip_buffers 16 8k;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        text/js
        text/xml
        text/javascript
        application/javascript
        application/json
        application/xml
        application/rss+xml
        image/svg+xml
        application/vnd.ms-fontobject
        font/eot
        font/otf
        font/ttf
        application/octet-stream;

    # Order is important, the more specific first
    
    location ~ ^/info/licenses(/|$) {
    return 301 http://oc.bydata.de/sharing/articles/licenses$is_args$args;
    }
    
    location ~ ^/info/definition(/|$) {
    return 301 http://oc.bydata.de/sharing/articles/definition$is_args$args;
    }
    
    location ~ ^/info/metadata(/|$) {
    return 301 http://oc.bydata.de/sharing/articles/metadata$is_args$args;
    }
    
    location ~ ^/info/provisioning(/|$) {
    return 301 http://oc.bydata.de/sharing/articles/provisioning$is_args$args;
    }
    
    location ~ ^/info/hvd(/|$) {
    return 301 http://oc.bydata.de/sharing/handouts/hvd$is_args$args;
    }
    
    location ~ ^/info/inventory(/|$) {
    return 301 http://oc.bydata.de/sharing/handouts/inventory$is_args$args;
    }

    location ~ ^/info(/|$) {
        return 301 http://oc.bydata.de/sharing$is_args$args;
    }
    location ~ ^/usage(/|$) {
    return 301 http://oc.bydata.de/using$is_args$args;
    }
    
    location ~ ^/events/open-data-day-muenchen-2024(/|$) {
    return 301 http://oc.bydata.de/using/events$is_args$args;
    }

    location / {
        try_files $uri $uri/ /index.html;
        add_header Access-Control-Allow-Origin *;
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}


map $http_x_forwarded_for $ip_anonym1 {
 default 0.0.0;
 "~(?P<ip>(\d+)\.(\d+))\.\d+\.\d+" $ip;
 "~(?P<ip>[^:]+:[^:]+):" $ip;
}

map $http_x_forwarded_for $ip_anonym2 {
 default .0;
 "~(?P<ip>(\d+)\.(\d+))\.\d+\.\d+" .0.0;
 "~(?P<ip>[^:]+:[^:]+):" ::;
}



map $ip_anonym1$ip_anonym2 $ip_anonymized {
 default 0.0.0.0;
 "~(?P<ip>.*)" $ip;
}

log_format  anonymized  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$ip_anonymized"';


access_log /var/log/nginx/access.log anonymized;

